openapi: 3.0.3
info:
  title: Inventory Management Plugin
  description: A plugin is designed to create and manage inventory lists using ChatGPT.
  version: "v1"
servers:
  - url: http://localhost:8090
paths:
  /api/collections/inventory/records:
    get:
      operationId: getInventories
      summary: Get the list of inventories
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getInventoriesResponse"
    post:
      operationId: addInventories
      summary: Add a inventory to the list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addInventoryRequest"
      responses:
        "200":
          description: OK

  /api/collections/inventory/records/{id}:
    patch:
      operationId: updateInventory
      summary: Update a inventory from the list
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The id of the inventory.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/patchInventoryRequest"
      responses:
        "200":
          description: OK

    delete:
      operationId: deleteInventory
      summary: Delete a inventory from the list
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The id of the inventory.
      responses:
        "200":
          description: OK

components:
  schemas:
    # 在庫を取得するAPIのレスポンス
    getInventoriesResponse:
      type: object
      properties:
        items:
          type: array
          description: The list of inventories.
          items:
            allOf:
              - type: object
                properties:
                  id:
                    $ref: "#/components/schemas/InventoryId"
                  collectionId:
                    $ref: "#/components/schemas/InventoryCollectionId"
                  collectionName:
                    $ref: "#/components/schemas/InventoryCollectionName"
                  series:
                    $ref: "#/components/schemas/InventorySeries"
                  name:
                    $ref: "#/components/schemas/InventoryName"
                  jancode:
                    $ref: "#/components/schemas/InventoryJanCode"
                  type:
                    $ref: "#/components/schemas/InventoryType"
                  count:
                    $ref: "#/components/schemas/InventoryCount"

    # 在庫を追加するAPIのリクエスト
    addInventoryRequest:
      type: object
      required:
        - series
        - name
        - jancode
        - type
        - count
      properties:
        series:
          $ref: "#/components/schemas/InventorySeries"
        name:
          $ref: "#/components/schemas/InventoryName"
        jancode:
          $ref: "#/components/schemas/InventoryJanCode"
        type:
          $ref: "#/components/schemas/InventoryType"
        count:
          $ref: "#/components/schemas/InventoryCount"

    # 在庫を更新するAPIのリクエスト
    patchInventoryRequest:
      type: object
      required:
        - series
        - name
        - jancode
        - type
        - count
      properties:
        series:
          $ref: "#/components/schemas/InventorySeries"
        name:
          $ref: "#/components/schemas/InventoryName"
        jancode:
          $ref: "#/components/schemas/InventoryJanCode"
        type:
          $ref: "#/components/schemas/InventoryType"
        count:
          $ref: "#/components/schemas/InventoryCount"

    InventoryId:
      type: string
      example: RECORD_ID
      description: The id of the inventory.

    InventoryCollectionId:
      type: string
      example: bvbq301xqrxyhes
      description: The collection id of the inventory.

    InventoryCollectionName:
      type: string
      example: inventory
      description: The collection name of the inventory.

    InventorySeries:
      type: string
      example: Apple Watch
      description: The series of the inventory.

    InventoryName:
      type: string
      example: Apple Watch Series 6
      description: The name of the inventory.

    InventoryJanCode:
      type: string
      example: 1234567890123
      description: The jan code of the inventory.

    InventoryType:
      type: string
      example: product
      enum:
        - product
        - material
      description: The type of the inventory.

    InventoryCount:
      type: integer
      example: 12
      description: The count of the inventory.
